name: api_craft
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  extended_text_field: ^16.0.2
  flutter_riverpod: ^3.0.3
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  super_context_menu: ^0.9.1
  suryaicons: ^0.0.3
  sqflite: ^2.4.2
  uuid: ^4.5.2
  linked_scroll_controller: ^0.2.0
  lazy_load_indexed_stack: ^1.2.1
  dio: ^5.9.0
  multi_split_view: ^3.6.1
  flutter_popup: ^3.3.9
  window_manager: ^0.5.1
  flutter_typeahead: ^5.2.0
  extended_text: ^15.0.2
  json_path: ^0.9.0
  collection: ^1.19.1
  # bitsdojo_window: ^0.1.6
  material: ^1.0.1
  xpath_selector: ^3.0.2
  xml: ^6.6.1
  # flutter_code_editor: ^0.3.5
  # flutter_highlight: ^0.7.0
  # highlight: ^0.7.0
  intl: ^0.19.0
  code_forge: ^4.0.0
  # code_forge: 
  #   path: ../../git/code_forge
  re_highlight: ^0.0.3
  flutter_js: ^0.8.1
  web_socket_channel: ^3.0.3
  crypto: ^3.0.7
  dotted_decoration: ^2.0.0
  file_picker: ^10.3.8
  desktop_drop: ^0.7.0
  mime: ^2.0.0
  flutter_svg: ^2.2.3
  json_explorer: ^0.1.2
  provider: ^6.1.5+1
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.3

flutter:
  uses-material-design: true
